url:
    canonical: example-site-single-language
    extra: []

httpauth:
    username: user
    password: pass

locale: cs_CZ

data:
    products: products.yml

form:
    contact:
        success_flash_message: Děkujeme za Vaší zprávu.
        handlers:
            -   type: email
                from:
                    name: MCS example-2 site
                    address: example-2@mcs.com
                recipients:
                    to: [ test.1@visionapps.cz ]
                    bcc: [ test.2@visionapps.cz ]
                templates:
                    subject: email/subject.html.twig
                    body: email/body.html.twig
            -   type: log
                file: form.log
        fields:
            name:
                - NotBlank: ~
            email:
                - NotBlank: ~
                - Email:
                    checkMX: true
            message:
                - NotBlank: ~

router:
    index: /
    product: /zbozi/{product_slug | products:slug}
    contact: /kontakt

redirect:
    /test/url1: /zbozi/mrkev

renderer:
    index: index.html.twig
    product: product.html.twig
    contact: contact.html.twig
